config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  get '/about' => 'pages#about'
  resources :users, :only => [:new, :create, :index]
  get 'session/new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  resources :sports, :only => [:show, :index]
  get '/sports' => 'sports#index'
  get '/my-events' => 'events#userEvents'


  resources :events, :only => [:new, :create, :index, :show]
  get '/events' => 'events#index'
  resources :events do
    member do
      get 'join'
      get 'leave'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :sport, :optional => true
    has_and_belongs_to_many :users 
end

app/models/sport.rb
class Sport < ApplicationRecord
    has_many :events
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_and_belongs_to_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    private
    def fetch_user
        @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
        session[:user_id] = nil unless @current_user.present? # Log out non-existent users.
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :check_for_login

    def index
        @events = Event.all
       
    end

    def userEvents
        @events = @current_user.events
    end

    def show
        @event = Event.find params[:id] 
        @users = @event.users
    end

    def new
        @event = Event.new
    end

    def create
        event = Event.create(event_params) 
        @current_user.events << event
        redirect_to events_path
    end
    
    def join
        @event = Event.find params[:id]
        @current_user.events << @event
        redirect_to @event
    end

    def leave
        @event = Event.find params[:id]
        @current_user.events.delete(@event)
        redirect_to @event
    end


    private
    def event_params
        params.require(:event).permit(:title, :appointed, :description, :arrival_time, :sport_id, :lat, :lng)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password"
      redirect_to login_path # try again
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
    def index
        @sports = Sport.all
    end

    def show
        @sport = Sport.find params[:id]
        @event = Event.new
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id # log in the new user
      redirect_to root_path # IRL: choose where to redirect
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1 class =" my-5 ">All events </h1>

<div class="sport-events row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 d-flex align-items-stretch">
    <% @events.each do |event| %>
    <div class="col">
        <div class="card shadow-sm">
        <div class="card-body">
            <h5 class="card-title"><%= link_to event.title, event, :class => 'text-decoration-none link-dark ' %></h5>
           
            <%# <h3>insert sport tile</h3> %>
            
            <div class="d-flex justify-content-between align-items-center">
            </div>
        </div>
    </div>
    </div>

    <% end %>
   
</div>

app/views/events/show.html.erb
<h1 class = " my-5 "><%= @event.title %></h1>
<p><%= @event.description %></p>
<p><%= @event.arrival_time %></p>


 <% if @event.sport.present? %>
       <li>sport: <%= link_to @event.sport.title, @event.sport %></li>
       <%= link_to image_tag(@event.sport.image, :class => 'thumb'), 
       @event.sport%>
       <div id="map" data-lat=<%= @event.lat %> data-lng=<%= @event.lng %>></div>
 <% end %>


    <ul>
    <% @users.each do |user| %>
        <li><%= user.name %></li>
    <% end %>
    </ul>

 

<%= link_to 'join', join_event_path(@event) %>
<%= link_to 'leave', leave_event_path(@event) %>


<%= javascript_include_tag "map" %>
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCTUMfXXNvknaNbixTNuJfu77k8EG7YaSw&callback=initMap" %>

app/views/events/userEvents.html.erb
<h1 class = " my-5 ">My events </h1>

<div class="sport-events row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 d-flex align-items-stretch">
    <% @events.each do |event| %>
    <div class="col">
     <div class="card shadow-sm">
        <div class="card-body">
            <h5 class="card-title"><%= link_to event.title, event, :class => 'text-decoration-none link-dark' %></h5>
            <div class="d-flex justify-content-between align-items-center">
            </div>
        </div>
    </div>
    </div>
    <% end %>
</div>
<div class="container ">
     <%= image_tag "/images/sports/colorSport.jpg", :class =>"img-fluid" %>
</div>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickUpGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="bg-dark collapse show" id="navbarHeader" style="">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white mb-4">Pick up game</h4>
              <p class="text-muted ">Take your workout to a new level, try something new! Moreover, training outdoors is an excellent opportunity to meet new people while performing your workout!</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <ul class="list-unstyled">
                <li><a <%=link_to "Home", root_path, :class => "text-white h4 mb-2" %>></a></li>
                <li><a <%= link_to 'About us', about_path, :class => "text-white mb-2"%>></a></li>
                <% if @current_user.present? %>
                <li><a <%= link_to 'Sports', sports_path, :class => "text-white mb-2" %>></a></li>
                <li><a <%= link_to 'All Events', events_path, :class => "text-white mb-2" %>></a></li>
                <li><a <%= link_to 'My events', '/my-events', :class => "text-white mb-2" %>></a></li>
                <li><a <%= link_to "Sign out", login_path, :method => 'delete', :class => "text-white mb-2" %>></a></li>
                <% else %>
                <li><a <%= link_to 'Sign up', new_user_path, :class => "text-white mb-2" %>></a></li>
                <li><a <%= link_to 'Log in', login_path, :class => "text-white mb-2" %>></a></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24">
            <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="true" aria-label="POTATO">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
</header>

    <div class="container">
      <%= yield %>
    </div>
    
    <div class="container">
      <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
          <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
          </a>
          <span class="text-muted">© 2022 Gissell, Inc</span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3"><a class="text-muted" > 
            <%= link_to "http://www.facebook.com/user" do %>
            <%= image_tag '/images/sports/facebook.png', height: 14 %>
            <% end %>
         </li>
          <li class="ms-3"><a class="text-muted">
            <%= link_to "http://www.instagram.com/user" do %>
            <%= image_tag '/images/sports/instagram.jpg', height: 14 %>
            <% end %></li>
          <li class="ms-3"><a class="text-muted">
            <%= link_to "http://www.twitter.com/user" do %>
            <%= image_tag '/images/sports/twitter.png', height: 14 %>
            <% end %></li>
          </li>
        </ul>
       
      </footer>
    </div>


   
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="my-5">About pick up game</h1>
<p>It is a long established fact that a 
    reader will be distracted by the
    readable content of a page when looking at its layout.
    The point of using Lorem Ipsum is that it has a more-or-less
    normal distribution of letters, as opposed to using
    'Content here, content here', making it look like readable English.
    Many desktop publishing packages and web page editors now use
    Lorem Ipsum as their default model text, and a search for
    'lorem ipsum' will uncover many web sites still in their infancy.
    Various versions have evolved over the years, sometimes by accident, 
    sometimes on purpose (injected humour and the like).
</p>

app/views/pages/home.html.erb
    <div class="px-4 py-5 my-5  text-center">
        <img class="d-block mx-auto mb-4" src="/images/sports/FallSportsIcon.png" alt="" width="72" height="57">
        <h1 class="display-5 fw-bold">Pick up Game </h1>
        <% if @current_user.present? %>
            <h2>Welcome back <%= @current_user.email %></h2>
        <% end %>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">In this spaces you can created events or join to an already created</p>
            <div class="d-grid gap-2 mb-5 d-sm-flex justify-content-sm-center">
                <button type="button" class="btn btn-outline-dark btn-lg px-4 gap-3 "><%= link_to 'Sign up', new_user_path, :class => 'nav' %></button>
                <button type="button" class="btn btn-outline-dark btn-lg px-4 "><%= link_to 'Log in', login_path, :class => 'nav' %> </button>
            </div>
            <div class="d-flex justify-content-center">
                <%= image_tag "/images/sports/siluetas.jpeg", height: 700 %>
            </div>
        </div>
   </div>

app/views/session/new.html.erb
<div class="row justify-content-md-center ">
 <div class="login-box mt-2 mb-5">
    <img class="d-block mx-auto mb-4" src="/images/sports/FallSportsIcon.png" alt="" width="72" height="57">
  <div class="row justify-content-md-center my4">
    <div class="login-box mt-2">
        <h1>Log In</h1>

        <% if flash[:error].present? %>
            <h2><%= flash[:error] %></h2>
        <% end %>
        <%= form_tag login_path do %>
            <%= label_tag :email, nil, :class => 'form-label'%>
            <%= email_field_tag :email, nil, :class => 'form-control'  %>
            <%= label_tag :password, nil, :class => 'form-label'%>
            <%= password_field_tag :password, nil, :class => 'form-control mb-2'  %>
            <%= submit_tag "Log in", :class => 'btn btn-outline-dark btn-lg' %>
        <% end %>
    </div>
  </div>
 </div>
   <div class="d-flex justify-content-center">
         <%= image_tag "/images/sports/siluetas.jpeg", height: 700 %>
    </div>
</div>

app/views/sports/index.html.erb
<h1 class=" my-5 ">All our sport</h1>


<div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3 d-flex align-items-stretch">
    <% @sports.each do |sport| %>
    <div class="col">
        <div class="card shadow-sm">
        <%= link_to  image_tag(sport.image, :class => 'thumb'), sport %>

        <div class="card-body">
            <h5 class="card-title"><%= link_to sport.title, sport, :class => 'text-decoration-none link-dark' %></h5>
            <div class="d-flex justify-content-between align-items-center">
            </div>
        </div>
    </div>
    </div>

    <% end %>
</div>
        
        

app/views/sports/show.html.erb
<h1 class=" my-5 "><%= @sport.title %></h1>

<%= image_tag @sport.image, :class => 'feature my-5 '%>

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3">
 <h3 class=" my-3 ">Ready for play outside, create an event and invite some friends</h3>
 <%= form_for @event do |f| %>
    <%= f.label :title, 'Event title', :class => 'form-label' %>
    <%= f.text_field :title, :class => 'form-control' %>
    <%= f.hidden_field :sport_id, :value => @sport.id %>
    <%= f.hidden_field :lat, :id => 'lat' %>
    <%= f.hidden_field :lng, :id => 'lng' %>

    <%= f.label :appointed, 'Date of event', :class => 'form-label' %>
    <%= f.text_field :appointed, :placeholder => 'YYYY-MM-DD', :class => 'form-control' %>
 
    <%= f.label :description, :class => 'form-label'%>
    <%= f.text_area :description, :class => 'form-control'%>

    <%= f.label :arrival_time, 'Arrival time', :class => 'form-label' %>
    <%= f.time_field :arrival_time, :class => 'form-control' %>

    <%=  f.submit "Create Event", :class => 'btn btn-outline-dark btn-lg my-5' %>
<% end %> 
<div id="map"></div>
</div>

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <h3 class=" my-5 ">Eventos disponibles </h3>
    <div class="sport-events row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 d-flex align-items-stretch">
        <% @sport.events.each do |event| %>
        <div class="col">
            <div class="card shadow-sm">
            <div class="card-body">
                <h5 class="card-title"><%= link_to event.title, event, :class => 'text-decoration-none link-dark' %></h5>
                <div class="d-flex justify-content-between align-items-center">
                </div>
            </div>
        </div>
        </div>

        <% end %>
    </div>
</div>
<%= javascript_include_tag 'mapForm'%>
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCTUMfXXNvknaNbixTNuJfu77k8EG7YaSw&callback=initMap" %>

    
  

app/views/users/index.html.erb
<h1> All users </h1>
<% @users.each do |user| %>
    <p><%= user.email %></p>
<% end %>

app/views/users/new.html.erb
<div class="row justify-content-md-center ">
 <div class="login-box mt-2 mb-5">
    <img class="d-block mx-auto mb-4" src="/images/sports/FallSportsIcon.png" alt="" width="72" height="57">
    <div class= "justify-content-md-center my-4"  >
        <h1 class="h3 mb-3 justify-content-center">Sign Up</h1>
    <% if @user.errors.any? %>
        <ol>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ol>
    <% end %>
    <%= form_for @user do |f| %>
        <%= f.label :email, :class => 'form-label' %>
        <%= f.email_field :email, :class => 'form-control' %>
        <%= f.label :password, :class => 'form-label' %>
        <%= f.password_field :password, :class => 'form-control' %>
        <%= f.label :password_confirmation, :class => 'form-label' %>
        <%= f.password_field :password_confirmation, :class => 'form-control mb-2' %>
        <%= f.submit "Welcome", :class => 'btn btn-outline-dark btn-lg' %>
    <% end %>
    </div>
 </div>
    <div class="d-flex justify-content-center">
         <%= image_tag "/images/sports/siluetas.jpeg", height: 700 %>
    </div>
</div>